// app/components/SpaceCard.vue
<script setup lang="ts">
import type { SpaceInfo } from '#shared/types/spaces'

const emit = defineEmits<{
  (e: 'onReserve', spaceInfo: SpaceInfo): void
}>()

const props = defineProps<SpaceInfo>()

</script>

<template>
  <UCard class="w-full max-w-2xs rounded-md shadow-md border border-black/10 dark:border-white/10">
    <template #header>
      <div class="flex items-center gap-4">
        <div class="w-8 h-8 rounded-[8px] bg-indigo-100 dark:bg-indigo-900 flex items-center justify-center text-indigo-600 dark:text-indigo-400 shrink-0">
          <Icon name="uil:desktop" size="16" />
        </div>
        <div>
          <p class="text-[10px] font-bold text-neutral-500 tracking-wider uppercase mb-0.5">Laboratório</p>
          <h3 class="text-[14px] font-bold text-neutral-800 dark:text-neutral-200 leading-tight">{{ props.name.charAt(0).toUpperCase() + props.name.slice(1) }}</h3>
        </div>
      </div>
    </template>

    <div class="space-y-2">
      <!-- Capacity box -->
      <div class="border border-neutral-300 dark:border-neutral-700 shadow-sm rounded-sm px-3 py-2 flex items-center gap-2 bg-neutral-100 dark:bg-neutral-900">
        <div class="w-8 h-8 rounded-xl bg-neutral-50 dark:bg-neutral-900 flex items-center justify-center text-neutral-500 shrink-0">
          <Icon name="i-lucide-users" size="16" />
        </div>
        <div>
          <p class="text-[9px] font-bold text-neutral-500 tracking-wider uppercase mb-0.5">Capacidade</p>
          <p class="text-[12px] font-bold text-neutral-800 dark:text-neutral-200">{{ capacity }} lugares</p>
        </div>
      </div>

      <!-- Resources box -->
      <div class="border border-neutral-300 dark:border-neutral-700 shadow-sm rounded-sm py-2 px-4 bg-neutral-100 dark:bg-neutral-900">
        <div class="flex items-center gap-2 mb-3">
          <Icon name="i-lucide-box" class="text-neutral-500" size="16" />
          <p class="text-[9px] font-bold text-neutral-500 tracking-wider uppercase">Recursos Incluídos</p>
        </div>
        <div v-if="resources && resources.length > 0" class="flex flex-wrap gap-2">
          <UBadge
            v-for="res in resources"
            :key="res"
            variant="solid"
            class="px-2.5 py-1 text-[11px] font-medium text-neutral-800 dark:text-neutral-200 bg-neutral-50 dark:bg-neutral-800 ring-1 ring-neutral-200 dark:ring-neutral-800 shadow-sm"
          >
            {{ res }}
          </UBadge>
        </div>
        <div v-else class="text-[11px] text-neutral-400 font-medium">
          Nenhum recurso incluído.
        </div>
      </div>
    </div>

    <template #footer>
      <div>
        <UButton
          block
          size="md"
          color="primary"
          variant="subtle"
          class="rounded-md font-bold shadow-sm"
          :ui="{ base: 'rounded-md cursor-pointer' }"
          @click="emit('onReserve', props)"
        >
          Reservar Agora
        </UButton>
      </div>
    </template>
  </UCard>
</template>

// src/components/home/SpaceCard.tsx
import { Box, Users } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

import { Field, FieldContent, FieldLabel } from "@/components/ui/field";

export type ListData = {
  id: number;
  name: string;
};

export type SpaceCardProps = {
  id: number;
  name: string;
  capacity: number;
  description: string | undefined;
  subjects?: ListData[] | undefined;
  resources?: ListData[] | undefined;
  locked: boolean;
  onReserve: () => void;
};

export function SpaceCard(props: SpaceCardProps) {
  const { name, capacity, description, resources, subjects, locked, onReserve } = props;

  return (
    <Card className="min-w-72 max-w-72 min-h-72 bg-white dark:bg-white/5 rounded-md border dark:border-violet-500/10 shadow-md hover:shadow-lg p-4 dark:shadow-violet-300/15">
      <CardHeader className="border-0 p-0 flex flex-row items-start justify-between">
        <div>
          <CardTitle className="text-lg font-bold text-neutral-900 dark:text-neutral-100">
            <span className="line-clamp-1" title={name}>
              {name}
            </span>
          </CardTitle>
          <CardDescription className="text-sm text-neutral-500 dark:text-neutral-400 line-clamp-1">
            {subjects?.length ? subjects.map((s) => s.name).join(", ") : "---"}
          </CardDescription>
        </div>
        <CardAction>
          <Badge
            variant="outline"
            className="border-emerald-500/30 bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300 dark:border-emerald-500/30 rounded-full px-2.5 py-0.5 text-xs font-normal"
          >
            {locked ? "Bloqueado" : "Disponível"}
          </Badge>
        </CardAction>
      </CardHeader>

      <CardContent className="flex flex-col gap-y-2.5 p-0 mt-3">
        <div className="flex items-center gap-2.5 text-sm text-neutral-700 dark:text-neutral-300">
          <Users className="size-4 shrink-0 text-violet-600 dark:text-violet-400" />
          <span className="font-medium ttext-neutral-900 dark:text-white">
            Capacidade:{" "}
            <strong className="font-semibold text-neutral-900 dark:text-neutral-100">{capacity} lugares</strong>
          </span>
        </div>
        {description && (
          <Field>
            <FieldLabel>
              <Box className="size-4 shrink-0 text-violet-600 dark:text-violet-400" />
              <span>Descrição</span>
            </FieldLabel>
            <FieldContent>
              <div className="flex items-start border rounded-md p-2">
                <span className="font-medium line-clamp-4 text-wrap truncate">• {description}</span>
              </div>
            </FieldContent>
          </Field>
        )}
        <Field>
          <FieldLabel>
            <Box className="size-4 shrink-0 text-violet-600 dark:text-violet-400" />
            <span>Recursos</span>
          </FieldLabel>
          <FieldContent>
            {resources && resources.length > 0 ? (
              <div className="flex flex-col items-start border rounded-md p-2">
                {resources.map((val, index) => {
                  if (index < 3) {
                    return (
                      <span className="flex gap-x-1">
                        •<strong className="font-medium text-neutral-900 dark:text-neutral-100">{val.name}</strong>
                      </span>
                    );
                  } else if (index === 3) {
                    return <span className="">...</span>;
                  }
                  return null;
                })}
              </div>
            ) : null}
          </FieldContent>
        </Field>
      </CardContent>

      <CardFooter className="bg-transparent border-0 mt-auto">
        <Button
          className="w-full h-10 rounded-xl bg-[#5925dc] hover:bg-[#4b1ec0] text-white font-medium shadow-sm transition-colors"
          onClick={onReserve}
        >
          Reservar
        </Button>
      </CardFooter>
    </Card>
  );
}
