// app/components/SpaceCard.vue
<script setup lang="ts">
import type { SpaceInfo } from '~~/types';

const emit = defineEmits<{
  (e: 'onReserve', spaceInfo: SpaceInfo): void
}>()

const props = defineProps<SpaceInfo>()
</script>

<template>
  <UCard class="rounded-2xl shadow-md border border-black/10">
    <template #header>
      <div class="flex items-center gap-4">
        <div class="w-12 h-12 rounded-[14px] bg-indigo-100 flex items-center justify-center text-indigo-600 shrink-0">
          <Icon name="uil:desktop" class="w-5.5 h-5.5" />
        </div>
        <div>
          <p class="text-[10px] font-bold text-neutral-500 tracking-wider uppercase mb-0.5">Laboratório</p>
          <h3 class="text-[1.1rem] font-bold text-neutral-900 leading-tight">{{ props.name.charAt(0).toUpperCase() + props.name.slice(1) }}</h3>
        </div>
      </div>
    </template>

    <div class="space-y-3">
      <!-- Capacity box -->
      <div class="border border-neutral-300 shadow-sm rounded-[14px] p-3 flex items-center gap-3 bg-neutral-100">
        <div class="w-10 h-10 rounded-xl bg-neutral-50 flex items-center justify-center text-neutral-500 shrink-0">
          <Icon name="i-lucide-users" class="w-5 h-5" />
        </div>
        <div>
          <p class="text-[9px] font-bold text-neutral-500 tracking-wider uppercase mb-0.5">Capacidade</p>
          <p class="text-[13px] font-bold text-neutral-800">{{ capacity }} lugares</p>
        </div>
      </div>

      <!-- Resources box -->
      <div class="border border-neutral-300 shadow-sm rounded-[14px] p-4 bg-neutral-100">
        <div class="flex items-center gap-2 mb-3">
          <Icon name="i-lucide-box" class="w-4 h-4 text-neutral-500" />
          <p class="text-[9px] font-bold text-neutral-500 tracking-wider uppercase">Recursos Incluídos</p>
        </div>
        <div v-if="resources && resources.length > 0" class="flex flex-wrap gap-2">
          <UBadge
            v-for="res in resources"
            :key="res"
            variant="solid"
            class="px-2.5 py-1 text-[11px] font-medium text-neutral-600 bg-neutral-50 ring-1 ring-neutral-200 shadow-sm"
          >
            {{ res }}
          </UBadge>
        </div>
        <div v-else class="text-[11px] text-neutral-400 font-medium">
          Nenhum recurso incluído.
        </div>
      </div>
    </div>

    <template #footer>
      <div>
        <UButton
          block
          size="md"
          color="primary"
          variant="solid"
          class="rounded-full font-bold h-11 shadow-sm text-[14px]"
          :ui="{ base: 'rounded-full cursor-pointer bg-indigo-700 hover:bg-indigo-600 active:bg-indigo-600' }"
          @click="emit('onReserve', props)"
        >
          Reservar Agora
        </UButton>
      </div>
    </template>
  </UCard>
</template>

// src/components/space-card.tsx
import { Users, TestTube, Box } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";

export type SpaceCardProps = {
    name: string;
    capacity: number;
    resources: string[];
    onReserve: (name: string, capacity: number, resources: string[]) => void;
};

export default function SpaceCard({
    name,
    capacity,
    resources,
    onReserve,
}: SpaceCardProps) {
    const formattedName = name ? name.charAt(0).toUpperCase() + name.slice(1) : "";

    return (
        <Card className="flex flex-col h-full bg-background border-black/10 shadow-md hover:shadow-md transition-shadow overflow-hidden group">
            <CardHeader className="pb-4 border-b border-black/10 bg-muted/20">
                <div className="flex items-start justify-between gap-2">
                    <div className="flex items-center gap-3">
                        <div className="p-2.5 bg-primary/10 rounded-lg text-primary transition-colors group-hover:bg-primary group-hover:text-primary-foreground">
                            <TestTube className="w-5 h-5" />
                        </div>
                        <div className="flex flex-col gap-0.5">
                            <span className="text-[9px] font-bold uppercase tracking-widest text-muted-foreground">
                                Laboratório
                            </span>
                            <CardTitle className="text-lg font-bold text-foreground leading-none">
                                {formattedName}
                            </CardTitle>
                        </div>
                    </div>
                </div>
            </CardHeader>
            <CardContent className="flex-1 py-1 flex flex-col gap-2">
                {/* Capacidade */}
                <div className="flex items-center gap-3 bg-muted/30 p-2.5 rounded-lg border border-black/10 shadow-xs">
                    <div className="p-1.5 bg-background rounded-md shadow-sm border border-black/5 text-muted-foreground">
                        <Users className="w-4 h-4" />
                    </div>
                    <div>
                        <p className="text-[9px] font-bold uppercase text-muted-foreground">Capacidade</p>
                        <p className="text-sm font-semibold text-foreground leading-tight">{capacity} lugares</p>
                    </div>
                </div>

                {/* Recursos */}
                <div className="flex flex-col p-2.5 gap-2.5 rounded-lg border border-black/10 shadow-xs">
                    <div className="flex items-center gap-1.5">
                        <Box className="w-3.5 h-3.5 text-muted-foreground" />
                        <h4 className="text-[10px] font-bold uppercase text-muted-foreground tracking-wider">
                            Recursos Incluídos
                        </h4>
                    </div>
                    <div className="flex flex-wrap gap-1.5">
                        {resources.length > 0 ? (
                            resources.map((res) => (
                                <span
                                    key={res}
                                    className="inline-flex items-center px-2 py-0.5 rounded text-[11px] font-medium bg-secondary text-secondary-foreground border border-black/5 shadow-xs"
                                >
                                    {res}
                                </span>
                            ))
                        ) : (
                            <span className="text-xs text-muted-foreground italic px-1">Padrão</span>
                        )}
                    </div>
                </div>
            </CardContent>
            <CardFooter className="pt-2 border-black/10">
                <Button
                    className="w-full font-semibold shadow-sm cursor-pointer"
                    onClick={() => onReserve(name, capacity, resources)}
                >
                    Reservar Agora
                </Button>
            </CardFooter>
        </Card>
    );
}
